---
title: "GeoLab"
author: "Roman Andreev"
date: "24 01 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r, echo=FALSE}
library(dplyr)
library(leaflet)
library(rgdal)
library(tigris)
library(RColorBrewer)
library(ggplot2)
library(readr)
```
Тут реализация библиотеки leaflet для пометки маркером.

```{r}
leaflet() %>%
  addTiles() %>%
  addMarkers(lng = c(91.442380, 37.564741),
             lat = c(53.721190, 55.751346),
             popup = c("Абакан", "Москва"))
```

Следующая реализация осуществляет фильтрацию популяции регионов США.
Данные взяты с интернета в формате csv.

```{r}
county_counts <- read_csv('C:/Users/BlackHorror/Desktop/leaflet_examples-master/leaflet_demo_R/data/population.csv')

downloaddir<-getwd()
unzip('C:/Users/BlackHorror/Desktop/leaflet_examples-master/leaflet_demo_R/data/PA_Counties_clip.shp.zip', exdir=downloaddir, junkpaths=TRUE)

filename<-list.files(downloaddir, pattern=".shp", full.names=FALSE)
filename<-gsub(".shp", "", filename[1])

county_shapes<-readOGR(downloaddir, filename) 

pal <- colorNumeric(
  palette = "YlGn",
  domain = county_counts$total_pop
)

county_shapes <- geo_join(county_shapes, county_counts, by_sp="NAME" , by_df="NAME" )


# создание карты 
paHealth.map <- leaflet() %>%
  addProviderTiles('CartoDB.Positron') %>%
  setView(lng=-77.16048, lat=41.00000, zoom =7) %>%
  addPolygons(data = county_shapes,
              stroke = T, smoothFactor = 0.2, fillOpacity = 0.5,
              color = "#000000", weight = 2, 
              fillColor = ~pal(county_shapes$total_pop)
              # color = ~pal(states@data$DISTRICT_)
  )%>% 
  addLegend("bottomright", pal = pal, values = county_counts$total_pop,
            title = "County Population",
            opacity = 1
  )
```

```{r, echo=FALSE}
paHealth.map
```